# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -std=c++11
CC       = gcc.exe -masm=intel -m32 -std=c++11
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/programs/Dev-Cpp/MinGW64/lib" -L"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lgdi32  -lwinmm
INCS     = -I"D:/programs/Dev-Cpp/MinGW64/include" -I"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/programs/Dev-Cpp/MinGW64/include" -I"D:/programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
